import Star from '../star/index';

const Twinkle = () => {
  return (
    <>
      <Star
        svgName="star-159"
        className="star"
        figmaSize={30}
        figmaLeft={552}
        figmaTop={181}
        fill="#220EFC"
      />
      <Star
        svgName="star-171"
        className="star"
        figmaSize={55}
        figmaLeft={235}
        figmaTop={431}
        fill="#DEFF81"
      />
      <Star
        svgName="star-101"
        className="star"
        figmaSize={24}
        figmaLeft={297}
        figmaTop={346}
        fill="#FF04C8"
      />
      <Star
        svgName="star-15"
        className="star"
        figmaSize={28}
        figmaLeft={457}
        figmaTop={662}
        fill="#FFFFFF"
      />
      <Star
        svgName="star-104"
        className="star"
        figmaSize={24}
        figmaLeft={526}
        figmaTop={721}
        fill="#FFF504"
      />
      <Star
        svgName="star-84"
        className="star"
        figmaSize={8}
        figmaLeft={254}
        figmaTop={686}
        fill="#F9F9F9"
      />
      <Star
        svgName="star-19"
        className="star"
        figmaSize={28}
        figmaLeft={193}
        figmaTop={704}
        fill="#D2D2D2"
      />
      <Star
        svgName="star-16"
        className="star"
        figmaSize={47}
        figmaLeft={325}
        figmaTop={784}
        fill="#FF5F05"
      />
      <Star
        svgName="star-102"
        className="star"
        figmaSize={25}
        figmaLeft={1621}
        figmaTop={232}
        fill="#FF5F05"
      />
      <Star
        svgName="star-18"
        className="star"
        figmaSize={25}
        figmaLeft={1705}
        figmaTop={281}
        fill="#CECECE"
      />
      <Star
        svgName="star-14"
        className="star"
        figmaSize={68}
        figmaLeft={1410}
        figmaTop={437}
        fill="#07FF6A"
      />
      <Star
        svgName="star-162"
        className="star"
        figmaSize={17}
        figmaLeft={1731}
        figmaTop={490}
        fill="#E6E6E6"
      />
      <Star
        svgName="star-85"
        className="star"
        figmaSize={8}
        figmaLeft={1775}
        figmaTop={513}
        fill="#F9F9F9"
      />
      <Star
        svgName="star-161"
        className="star"
        figmaSize={13}
        figmaLeft={1532}
        figmaTop={630}
        fill="#DFB750"
      />
      <Star
        svgName="star-103"
        className="star"
        figmaSize={25}
        figmaLeft={1598}
        figmaTop={742}
        fill="#220EFC"
      />
      <Star
        svgName="star-160"
        className="star"
        figmaSize={29}
        figmaLeft={1457}
        figmaTop={842}
        fill="#FF04C8"
      />
      <Star
        svgName="star-87"
        className="star"
        figmaSize={8}
        figmaLeft={1434}
        figmaTop={829}
        fill="#FFF2F2"
      />
      <Star
        svgName="star-170"
        className="star"
        figmaSize={55}
        figmaLeft={1337}
        figmaTop={718}
        fill="#FF04C8"
      />
    </>
  );
};

export default Twinkle;
